import { QueryColumn } from "./entities";

export function sqlCalc(f: string, params: {[name: string]: QueryColumn}): QueryColumn;
export function sqlCalc(f: string, params: QueryColumn[]): QueryColumn;
export function sqlCalc(f: string, ...params: QueryColumn[]): QueryColumn;
export function sqlCalc(f: string, params: any): QueryColumn {
	//QueryColumn generated by thi method MUST be aliased. So use a static uid to make sure it is:
	//new QueryColumn(null, null, computedSql).as("SQL_CALC_" + uid++);
	throw new Error("TODO")
}



